name: Build App
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v2
      - name: Print current directory
        run: pwd
      - name: List directories
        run: ls
      - name: List directories in dotnet Api 
        run: ls CrossFitLibrary.Api -R
      - name: Running dotnet build
        run: dotnet build
      - name: Checking NPM verion 
        run: npm -v
